baseURL = "https://hyennnlog.kr/"
languageCode = "ko-kr"
title = "ì—„ë§ˆ, ë‚´ ëˆˆì€ ì–¸ì œ í•˜íŠ¸ë¡œ ë³€í•´ìš”"
theme = "hugo-coder"

[pagination]
  pagerSize = 10

[params]
  author = "ê¹€í˜œì§„"
  description = "hyennn.log"

  customCSS = ["css/custom.css", "css/photos.css"]

[menu]
  [[menu.main]]
    name = "Cinema"
    url = "/cinema/"
    weight = 10

  [[menu.main]]
    name = "Book"
    url = "/book/"
    weight = 20


  [[menu.main]]
    name = "Photo"
    url = "/photos/"
    weight = 30

  [[menu.main]]
    name = "Sketch"
    url = "/sketch/"
    weight = 40

  [[menu.main]]
    name = "BecomingğŸï¸"
    url = "/kimgyeul/"
    weight = 50

[markup.goldmark.renderer]
  unsafe = true
