baseURL = "https://hyennnlog.netlify.app/"
title = "KIMHYEJIN"
theme = "hugo-coder"

[markup.goldmark.renderer]
unsafe = true

[pagination]
  pagerSize = 20

contentDir = "content"

[params]
  author = ""
  avatarURL = "images/profile.png"
  since = "2025"
  description = "hyennn.log"
  keywords = "blog, personal"
  info = [
    "å­£ç¯€ã®ã¯ã˜ã¾ã‚Šã‚’ä¿¡ã˜ã¦ã¿ã‚ˆã†ã€‚",]

  # âœ… CSS ì¶”ê°€ëŠ” ì—¬ê¸°!
 customCSS = ["css/custom.css", "css/fixes.css", "css/photos.css"]


[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram"
  weight = 1
  url = "https://www.instagram.com/hy_ennn/"

[menu]
  [[menu.main]]
    name = "Movie"
    pageRef = "/cinema"
    weight = 1

  [[menu.main]]
    name = "Book"
    pageRef = "/book"
    weight = 2

  [[menu.main]]
  name = "Archive"     
  pageRef = "/photos"
    weight = 3

  [[menu.main]]
    name = "Sketch"
    pageRef = "/Note"
    weight = 4

  [[menu.main]]
    name = "BecomingğŸï¸"
    pageRef = "/gyul"
    weight = 6
