baseURL = "https://hyennnlog.kr/"
languageCode = "ko-kr"
title = "HYENNN"
theme = "hugo-coder"

[pagination]
  pagerSize = 10

[params]
  author = ""
  description = "hyennn.log"

  customCSS = ["css/custom.css", "css/photos.css"]

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10


  [[menu.main]]
    name = "Cinema"
    url = "/cinema/"
    weight = 20

  [[menu.main]]
    name = "Book"
    url = "/book/"
    weight = 30


  [[menu.main]]
    name = "Photo"
    url = "/photos/"
    weight = 40

  [[menu.main]]
    name = "Sketch"
    url = "/sketch/"
    weight = 50

  [[menu.main]]
    name = "BecomingüéûÔ∏è"
    url = "/kimgyeul/"
    weight = 60

[markup.goldmark.renderer]
  unsafe = true
